CREATE TABLE dbo.mg_member (
    member_id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    member_agent_id SMALLINT,
    member_account VARCHAR(64) NOT NULL UNIQUE,
    member_nickname VARCHAR(64) NULL,
    member_level TINYINT NOT NULL,
    member_datetime DATETIME NOT NULL,
    member_update DATETIME NULL,
    member_gamemoney DECIMAL(19, 2) NOT NULL,
    member_charge_money DECIMAL(19, 2) NOT NULL,
    member_exchange_money DECIMAL(19, 2) NOT NULL,
    member_betting_money DECIMAL(19, 2) NOT NULL,
    member_betting_benefit_money DECIMAL(19, 2) NOT NULL,
    member_token VARCHAR(64) NULL,
    member_online CHAR(1) NOT NULL,
    member_status CHAR(1) NOT NULL,
    member_deny_chat DATETIME NULL,
    member_nickname_update DATETIME NULL,
    member_email VARCHAR(255) NOT NULL UNIQUE,
    member_email_status CHAR(1) NOT NULL,
    member_dob DATE NOT NULL,
    member_password VARCHAR(255) NOT NULL, 
);